### ISSUE TITLE
How to get notification while video playing ?

### ISSUE THREAD

**Issue by kristoff2016** [josejuanqm/VersaPlayer#10]
Hello thank you for your great plugin. I do love it 
I tired to get progress and duration total of videos but option in list features 
Please show me 
thank you

**Comment by josejuanqm** [comment]
Hi @kristoff2016 ,

VersaPlayerView has a playbackDelegate where you can get this information.

here's the link to the documentation:
https://josejuanqm.github.io/Libraries-Documentation/VersaPlayerCore/Classes/VersaPlayerView.html#/s:24VersaPlayeriOSDocProject0A10PlayerViewC16playbackDelegateAA0ae8PlaybackH0_pSgvp

**Comment by kristoff2016** [comment]
Hello, again
```
class VideosPlayer: VersaPlayerPlaybackDelegate {
    
     func startBuffering(layer: VersaPlayer) {
        print("startBuffering======")
    }

}

```
Delegate is not working. did I miss something or config somewhere ? Please help thank you so much again!

**Comment by kristoff2016** [comment]
Delegate is not listen Please help thank you

**Comment by kristoff2016** [comment]
If you have example in programming it really good

**Comment by josejuanqm** [comment]
Hi @kristoff2016 ,

What platform are you using?
You have a typo in your delegate, it shoud say “player: VersaPlayer)” but says, “layer: VersaPlayer)”.

Also, what version are you using?

Thanks!

**Comment by kristoff2016** [comment]
Hello there!
Currently, I Using VersaPlayer (2.1.3)
Make videos play

```
if let url = URL.init(string: "https://res.cloudinary.com/dyymcjwa2/video/upload/v1542594040/Pexels_Videos_1414530.mp4") {
            let item = VersaPlayerItem(url: url)
            playerView.set(item: item)
            playerView.use(controls: controls)

        }

```
```
class VideosPlayer: VersaPlayerPlaybackDelegate {
   func startBuffering(layer: VersaPlayer) {
        print("startBuffering======")
    }
}

```

I am building ios app 

thank you so much

**Comment by kristoff2016** [comment]
I also updated to VersaPlayer 2.1.4

**Comment by kristoff2016** [comment]
It's working now by just added  `playerView.playbackDelegate = self`
Thank you again. but another request it would be great if we have Delegate `stateChanged`
to controller isPlaying or Pause thank you

**Comment by josejuanqm** [comment]
Thanks @kristoff2016 will keep this in mind for the next release!
