### ISSUE TITLE
Video Controls not showing

### ISSUE THREAD

**Issue by omar-haris** [josejuanqm/VersaPlayer#12]
Hi everyone, @josejuanqm 

why video control not showing just video playing and no play or pause or seek bar ?

this is my code its same as example:

```
import UIKit
import VersaPlayer

class ViewController: UIViewController {

    @IBOutlet weak var playerView: VersaPlayerView!
    @IBOutlet weak var controls: VersaPlayerControls!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        if let url = URL.init(string:  "https://www.w3schools.com/html/movie.mp4") {
            let item = VersaPlayerItem(url: url)
            playerView.set(item: item)
        }
        
        playerView.layer.backgroundColor = UIColor.black.cgColor
        playerView.use(controls: controls)
    }

}
```

do i miss something ? show i enable or do more to show video controls ?

**Comment by danibachar** [comment]
As far as I checked there is not default UI implementation for the Controls View. 
I’m just about to finish such one, in a project I’m working on, and hope to PR it  to here.

**Comment by josejuanqm** [comment]
Hi @fiftysoft , there is no current default video controls, however i noticed that you have set an IBOutlet for the controls view. this view provides outlets to set your own play/pause button, slider, and so on.

Check the attributes inspector for all the available outlets

Thanks!

If this was any helpful, please close this issue.

**Comment by forTheSakeOfLogic** [comment]
The OP is referring to the code provided in the sample. This is NOT code that he wrote, this is the sample project provided here on Github and he is right, the player controls do not play by default.

**Comment by josejuanqm** [comment]
Hi @forTheSakeOfLogic,

I understand, however the controls view provides outlets to any control supported by VersaPlayer so no more configuration is needed.

See the example project for examples.

**Comment by forTheSakeOfLogic** [comment]
@jose-quintero I am looking at the example file right now, there are no attributes in the inspector pane.
<img width="1347" alt="screen shot 2018-12-20 at 9 24 05 am" src="https://user-images.githubusercontent.com/43387532/50290247-0c72ae00-0439-11e9-8cbe-7fe94bedc383.png">
