### ISSUE TITLE
having trouble adding controls to player

### ISSUE THREAD

**Issue by forTheSakeOfLogic** [josejuanqm/VersaPlayer#17]
Hi everyone, got the sample project to work, but no controls. how do I add controls to the player? do I have to do that programmatically or through storyboard?

can someone show one example of at least one control.

thank you

**Comment by josejuanqm** [comment]
Hi @forTheSakeOfLogic ,

Examples are available in the Examples folder,
Head over there to get an idea of how to create you own.

If this was any helpful please do close this issue.

**Comment by forTheSakeOfLogic** [comment]
Hi @jose-quintero 

I looked at the example iOS app. The controls dont show up. In a different post here, another person is having trouble with the same thing. What am I missing?

sorry for the bother.

**Comment by josejuanqm** [comment]
No trouble at all!

Let me check the examples and check why the controls aren’t showing.

I’ll get back to you today.

**Comment by forTheSakeOfLogic** [comment]
@josejuanqm thank you very much!

here are the images of what I am seeing.


<img width="1184" alt="screen shot 2018-12-20 at 9 26 39 am" src="https://user-images.githubusercontent.com/43387532/50290365-6f644500-0439-11e9-8369-82534b86b108.png">
<img width="1347" alt="screen shot 2018-12-20 at 9 24 05 am" src="https://user-images.githubusercontent.com/43387532/50290366-6f644500-0439-11e9-8807-160efdcbc9ec.png">

**Comment by forTheSakeOfLogic** [comment]
@josejuanqm was just wondering if you got a chance to check it out.

thnx

**Comment by forTheSakeOfLogic** [comment]
@josejuanqm here is what the controls view look like in Xcode. No outlets in the attributes inspector for controls.

<img width="1561" alt="screen shot 2018-12-22 at 2 11 59 pm" src="https://user-images.githubusercontent.com/43387532/50377881-aed69100-05f3-11e9-92cb-fe17f8290a8d.png">




thnx

**Comment by josejuanqm** [comment]
Hi @forTheSakeOfLogic ,

Sorry, I haven’t got time to get to this yet.

However i meant the connections inspector not the attributes inspector.

Ill try to check this today in the example project, but be sure to check the connections inpector.

**Comment by forTheSakeOfLogic** [comment]
@josejuanqm I see the outlets in the connection tab. thnx, But I genuinely do not know how to use them since there is no documentation on proper use. I assume that I had to connect them to buttons I create on the control view right? I tried that, it didnt work, the buttons dont do anything. I then tried adding buttons to main VC and connected them to these outlets, well something did happen now, a crash! Actually a crash at the right place it seems in that if I connected the button to the play/pause outlet for example, it would crash at the lines where you coded for that specific button. I tried connecting them straight to the controller view, cant do that. I tried connecting them straight to the player view and I get a crash at launch SIGABRT. HOW the hell do I use these outlets????

**Comment by josejuanqm** [comment]
@forTheSakeOfLogic 

Hey, honestly, I as open source dev do my best to maintain this repo. Being disrespectful won’t get anything done any quicker. I would appreciate it if you could be more mindful of that.

I updated the iOS example with controls added. If you ran into any trouble let me know.

**Comment by forTheSakeOfLogic** [comment]
@josejuanqm I want to start off by clarifying a few things, I was not trying to be disrespectful, nor do I understand where in the above message I was disrespectful. What I was, however, frustrated, not at you, but at my own ignorance/incompetence of not figuring it out. As for you, I have nothing but the highest respect for 1. spending the time to build this great project and providing it for free and 2. spending the time to continue to maintain it answer/fix issues. 

As for your update, it works perfectly! thank you!!!!!

you my dear friend, have my highest respect!

wishing you a wonderful holiday season.
