### ISSUE TITLE
Strong type delegate

### ISSUE THREAD

**Issue by rohankanoo** [josejuanqm/VersaPlayer#19]
Hey, VersaPlayerPlaybackDelegate is a strong type delegate thus preventing deinit of a ViewController from being called due to strong reference. Protocol should be class type and delegate should be weak. Can you please fix this issue at the earliest.

Thanks in advance.

**Comment by josejuanqm** [comment]
Hi @rohankanoo 

I merged a pr that should fix that.

Please do check again.

Thanks!
