### ISSUE TITLE
VersaPlayerPlaybackDelegate class type

### ISSUE THREAD

**Issue by rohankanoo** [josejuanqm/VersaPlayer#22]
Hey, please make VersaPlayerPlaybackDelegate of class type to avoid strong referencing. To change this please replace VersaPlayerPlaybackDelegate: AnyObject with VersaPlayerPlaybackDelegate: class

PFA fix screenshot.

![screen shot 2019-01-08 at 1 31 02 pm](https://user-images.githubusercontent.com/14327015/50817434-cc249280-1349-11e9-9f91-c829e62cd2c3.png)

Thanks

**Comment by josejuanqm** [comment]
Thanks!

**Comment by rohankanoo** [comment]
@josejuanqm You are welcome..!
