### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException' only on iOS 10.3.3

### ISSUE THREAD

**Issue by tarsemssw** [josejuanqm/VersaPlayer#30]
Tested with a provided example by running Target VersaPlayerTest_iOS

Steps to produce the crash: 
**Step 1.** Run project's target VersaPlayerTest_iOS on iOS 10.3.3 ( i used iPhone 6s)
**Step 2.** Tap on show video
**Step 3.** Tap on back button from the new view controller where the video is being played
and the app crashes!

**Note: the app is working fine on my iOS 12.1 device** 

**Crash Log:**

1 <VersaPlayer.VersaPlayerView: 0x107e1b450; frame = (0 0; 375 667); autoresize = RM+BM; layer = <CALayer: 0x170227300>>
2 <VersaPlayer.VersaPlayerControlsCoordinator: 0x107d113b0; frame = (0 0; 375 667); layer = <CALayer: 0x174225aa0>>
3 <VersaPlayer.VersaPlayerGestureRecieverView: 0x107e31820; frame = (0 0; 375 667); gestureRecognizers = <NSArray: 0x170247680>; layer = <CALayer: 0x17022d240>>
4 <VersaPlayer.VersaPlayerControls: 0x107e06230; frame = (0 0; 375 667); autoresize = RM+BM; layer = <CALayer: 0x170226ca0>>
5 VersaPlayer.VersaPlayerControlsBehaviour
6 <VersaPlayer.VersaPlayerRenderingView: 0x107e07d30; frame = (0 0; 375 667); layer = <CALayer: 0x170229260>>
7 <VersaPlayer.VersaPlayerLayer: 0x170241ef0>
8 <VersaPlayer.VersaPlayerItem: 0x17022bde0, asset = <AVURLAsset: 0x17022bcc0, URL = https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8>>
9 <VersaPlayer.VersaPlayer: 0x1702419b0>
2019-04-02 00:38:57.968270+0530 VersaPlayerTest_iOS[16838:11201971] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x1702419b0 of class VersaPlayer.VersaPlayer was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x174220180> (
<NSKeyValueObservance 0x170242970: Observer: 0x1702419b0, Key path: status, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x170242850>
)'
*** First throw call stack:
(0x1823defe0 0x180e40538 0x1823def28 0x182e3b160 0x180e5e134 0x1822bab28 0x18238acec 0x1822bada4 0x183d25074 0x188575c9c 0x100031928 0x1812c959c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by josejuanqm** [comment]
Thank you, will work on this once #29 is done.

**Comment by tarsemssw** [comment]
@josejuanqm don't want to bother, Just want to know if is there any progress/plan for the fix?

**Comment by josejuanqm** [comment]
@tarsemssw Should be fixed in 2.3.3 ! Thanks for the patience!
