### ISSUE TITLE
Landscape rotate

### ISSUE THREAD

**Issue by neodave** [josejuanqm/VersaPlayer#33]
My app is restricted to portrait, but I would like enable rotation to landscape when in full screen mode. I have not been able to find if an override is provided here. Does VersaPlayer address this sort of thing? Great framework btw..

**Comment by Eke** [comment]
Hello @neodave, i think you must manage rotation policy by yourself. For example you can allow rotation in view controller when player goes fullscreen.

**Comment by josejuanqm** [comment]
Hi @neodave , as @Eke points out, you need to provide your own rotation logic. VersaPlayer will only provide some help here. Basically the surface view and some other helpers.
