### ISSUE TITLE
Can I use Carthage?

### ISSUE THREAD

**Issue by mtangoo** [josejuanqm/VersaPlayer#35]
Could not believe cocoapods have to download ~500MB only to be able to install this library. I only use Carthage for all libraries in my project. Is it possible to use carthage in addition to pods?

**Comment by josejuanqm** [comment]
Hey, @mtangoo it should be available as of v.3.0.0 !

**Comment by mtangoo** [comment]
Thank you for the answer

**Comment by mtangoo** [comment]
I have unrelated request. Can you make a Youtube video on how to add Controls to Player? I tried to do it for almost a week without success. I had to temporarily abandon this and write my own ad-hoc player just to meet the deadline that had passed. Seems tricky to do!

**Comment by josejuanqm** [comment]
Sure I can!, I'll try to work on it this week.

**Comment by mtangoo** [comment]
Thank you!
