### ISSUE TITLE
How to pass header attributes?

### ISSUE THREAD

**Issue by khunshan** [josejuanqm/VersaPlayer#36]
You can send one using 'AVURLAssetHTTPHeaderFieldsKey' in AVPlayer. Does VersaPlayer support. If yes, how? Please guide with example. 

Cheers.

**Comment by josejuanqm** [comment]
Hi @khunshan ,

Sure!, AVPlayerItem can be initialized with a AVAsset, so you can pass a AVURLAsset configured with the proper headers.

```swift
let headers: [String:String] = [:]
let asset = AVURLAsset(url: url, options: ["AVURLAssetHTTPHeaderFieldsKey": headers])
let item = VersaPlayerItem(asset: asset)
playerView.set(item: item)
```
