### ISSUE TITLE
Can't initialize player, please help

### ISSUE THREAD

**Issue by mblrdev** [josejuanqm/VersaPlayer#39]
Hello! When I try to initialize the player in the vc, the app crashes with this error

`Thread 1: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value`
on playerView.layer.backgroundColor = UIColor.black.cgColor

I am doing exactly everything as the example code, I literally copied it.Also tried to clone the repo and run the example player, which works, but when I create a view controller in my app, and navigate to it the app still crashes...

Current code im using: 
`import UIKit
import VersaPlayer

class ViewController: UIViewController {
    
    @IBOutlet weak var playerView: VersaPlayerView!
    @IBOutlet weak var controls: VersaPlayerControls!
    
    @IBAction func trigger(_ sender: UIButton) {
        print("test")
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        playerView.layer.backgroundColor = UIColor.black.cgColor
        playerView.use(controls: controls)
        
        if let url = URL.init(string: "https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8") {
            let item = VersaPlayerItem(url: url)
            playerView.set(item: item)
        }
    }
    
    
}`

Also tried  version 2.2.3 of the player, and with swift 4 and 4.2, still no luck..

Any idea what could it be?

**Comment by josejuanqm** [comment]
Hi @mblrdev ,

Can you try checking whether VersaPlayer is set as the module of the view in the Identity Inspector?

Let me know.

**Comment by mblrdev** [comment]
No, should it be?

edit: tried to add it, still getting the same error

**Comment by josejuanqm** [comment]
Could you be able to send a code sample?

That way I can help you out. let me know!

**Comment by mblrdev** [comment]
Fixed, turns out I didn't add the outlets..Sorry, just new to swift..

Btw the player is perfect!Also do I still need a separate pod for the airplay extension?

**Comment by josejuanqm** [comment]
No you no longer need that :) should be good to go. 

Thank you!
