### ISSUE TITLE
IB Designables: Failed to render and update auto layout status for VersaPlayerControls (wWX-7i-SUK): Failed to launch designables agent. Check the console for a more detailed description and please file a bug report at feedbackassistant.apple.com.

### ISSUE THREAD

**Issue by valentcheung** [josejuanqm/VersaPlayer#40]
Xcode version: 11 Beta 2~4

There's a build error in red for the Full Screen Controls set stating: "IB Designables: Failed to render and update auto layout status for VersaPlayerControls (wWX-7i-SUK): Failed to launch designables agent. Check the console for a more detailed description and please file a bug report at feedbackassistant.apple.com."

The Full Screen Controls set were directly copied from the Example project file.

**Comment by josejuanqm** [comment]
Hi, This seems to be an Xcode Issue.. I'll take a look.
