### ISSUE TITLE
Unexpectedly found nil

### ISSUE THREAD

**Issue by asger777** [josejuanqm/VersaPlayer#43]
handler.playbackDelegate?.playbackReady(player: self)

sometimes it gives me this crash.
my apps first screen has one player, second screen has another player. when i push second and fast pop back, it gives me this crash.
![image](https://user-images.githubusercontent.com/23039633/63945602-a7ba2980-ca84-11e9-8115-d0b203f99a92.png)

**Comment by josejuanqm** [comment]
Hi @asger777 ,

Can you pinpoint the nil variable? is it handler?

Thanks

**Comment by asger777** [comment]
@josejuanqm , what means to pinpoint the nil variable ?

nil variable here is handler variable. its playerview.
and it happens when i open second screen and go back before completing installation of playerview

**Comment by josejuanqm** [comment]
Thanks @asger777 , will work on this.

**Comment by Koronaa** [comment]
Hey @josejuanqm ,

Any update on this? 

Awesome library btw. Keep up the good work.

**Comment by LastSoul** [comment]
i have the same problem

**Comment by josejuanqm** [comment]
Hi everyone, thank you for your patience. This was a mix of unreleased code changes and a minor update.

New version is published.

Please re-open this ticket as needed
