### ISSUE TITLE
how to add controls to player 

### ISSUE THREAD

**Issue by ahmedMaher3** [josejuanqm/VersaPlayer#49]
@josejuanqm I want to start off by clarifying a few things, I was not trying to be disrespectful, nor do I understand where in the above message I was disrespectful. What I was, however, frustrated, not at you, but at my own ignorance/incompetence of not figuring it out. As for you, I have nothing but the highest respect for 1. spending the time to build this great project and providing it for free and 2. spending the time to continue to maintain it answer/fix issues. 

As for your update, it works perfectly! thank you!!!!!

you my dear friend, have my highest respect!

wishing you a wonderful holiday season.

_Originally posted by @forTheSakeOfLogic in https://github.com/josejuanqm/VersaPlayer/issues/17#issuecomment-449618165_

**Comment by josejuanqm** [comment]
Hi @ahmedMaher3 , Could you please provide a clear description of your issue?

Are the sample controls not working for you?

Thanks!

**Comment by ahmedMaher3** [comment]
Hi @josejuanqm  iknow that no default controls but idont know how to add controls to my player 
are you add it by storyBoard or progamatically .
sorry for late for reply

**Comment by josejuanqm** [comment]
Hi @ahmedMaher3 ,

Controls can be added either by storyboard or programmatically, If you are to add them via storyboard you can create a UIView (you can check the sample project) and connect the player outlet to that view. Or create that view programmatically using VersaPlayerControls Class and add that to the player with `player.add(controls:)`
