### ISSUE TITLE
App crash while setting PlayerItem to Player.

### ISSUE THREAD

**Issue by StellarKuldeep** [josejuanqm/VersaPlayer#5]
First of thanks for the excellent library.

When I try to install it via pod it install with **"1.2.0"** and `VersaPlayerItem` becomes to `VPlayerItem` and when I see both files then there's only 1 line of code `public var isEncrypted: Bool = false`

when I use below code then it crash at `player.set(item: item)` line of code with below bad access error.

**`Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`**

```
override func viewDidLoad() {
        super.viewDidLoad()
        
        player.use(controls: controls)
        if let url = URL.init(string: "https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8") {
            let item = VPlayerItem(url: url)
            player.set(item: item)
        }
    }
```

do I miss something or is there any issue with version?

**Comment by josejuanqm** [comment]
Hi @StellarKuldeep ,

Thanks a lot! Appreciate it,

Have you tried cleaning the build folder? If you are seeing two files it could mean some indexing may have been there from the previous version.

Did you update the pod recently? Or is it a clean install?

Thanks!

**Comment by Michael24884** [comment]
I’m also receiving this error. There is also no VersaPlayerView

**Comment by josejuanqm** [comment]
Hi @Michael24884  ,

Did you tried cleaning the build folder?

Was this a update or a clean install?

**Comment by Michael24884** [comment]
Definitely cleaned. I even uninstalled and reinstalled the pod

**Comment by josejuanqm** [comment]
@Michael24884 if you are using Interface Builder, setting the Module manually to VersaPlayer fix this issue?

**Comment by josejuanqm** [comment]
@StellarKuldeep , @Michael24884 ,

Found the issue and uploaded a new version. Be sure to pull the v.1.2.1 and re-setting your class name on Interface Builder.

The issue was Interface Builder not correctly setting the Module to VersaPlayer when setting VersaPlayerView as the Class in the Identity Inspector.

**Comment by StellarKuldeep** [comment]
@josejuanqm App crash because of Module name. When I set VersaPlayer manually then it works.

Thanks for your suggestion.
You can close this question.

Again thanks for helpful library.
