### ISSUE TITLE
Video Keeps playing in Background after dismissing the ViewController

### ISSUE THREAD

**Issue by Ezimetjan** [josejuanqm/VersaPlayer#50]
When you enter fullscreen mode and back to normal mode.  then you dismiss or pop the viewController Player keeps playing in the background which leads me to think the playerView is not released from Memory.  This happens with the provided TestProject. 
I think there is a retain cycle issue with the  "nonFullscreenContainer"  property,  making it weak solved the problem for me.

**Comment by josejuanqm** [comment]
thank you! care to do a pr? @Ezimetjan

**Comment by Ezimetjan** [comment]
I just submitted a pull request.

**Comment by Ezimetjan** [comment]
> I just submitted a pull request.



> I just submitted a pull request.
