### ISSUE TITLE
Not scrolling if put in scrollview after VideoPlayerControls disappears

### ISSUE THREAD

**Issue by RajChanchal** [josejuanqm/VersaPlayer#51]
If I put VersaPlayer in scrollview, and if VideoPlayerControls view disappears, the scrolling doesn't work if the drag gesture starts from player's view. It does work if the dragging finger doesn't start from player but some other components of the scrollview. 

It does also work, if the controls are visible, as soon as they disappear, the scrolling no more works.

**Comment by josejuanqm** [comment]
@RajChanchal please confirm whether disabling the pan gesture fixes the issue.

**Comment by dev-dubaisoftwaresolutions** [comment]
You meant if there is a pen gesture attributed to VersaPlayer class?
If it was meant for scrollview I am using, then I don't want to disable pen gesture because I want the scrollview to scroll.

**Comment by RajChanchal** [comment]
You meant to say there is a pen gesture attributed to VersaPlayer class?
If it was meant for scrollview I am using, then I don't want to disable pen gesture because I want the scrollview to scroll.
But if there a pen gesture associated to something else, please let me know so that I can disable it.

**Comment by RajChanchal** [comment]
@josejuanqm I dug into the code and realized that disabling the pan gesture fixes the issue.

While instantiating the player view, I do the following:

```
if let swipeGesture = videoPlayer.controls.controlsCoordinator.gestureReciever.panGesture{
   videoPlayer.controls.controlsCoordinator.gestureReciever.removeGestureRecognizer(swipeGesture)
   videoPlayer.controls.controlsCoordinator.gestureReciever.panGesture = nil
}
```

Is it the correct way or there is some other way to remove a particular gesture?

**Comment by josejuanqm** [comment]
Hey @RajChanchal ,

There is no current way of removing the gesture easier. I'll try working on something this week.
In the meantime, does this fixes your issue?

Thanks!

**Comment by RajChanchal** [comment]
Hello @josejuanqm , yes it fixed my issue. Usually the use case is, you can put the player in tableview cells and they are prone to be scrolled.
If a video is playing and you want to scroll, it is impossible currently because the pan gesture is being consumed. Thanks for looking at it this week.

**Comment by RajChanchal** [comment]
@josejuanqm have you resolved it in the new update?

**Comment by NikhilGangurde** [comment]
Any solution on this one I am still facing a similar issue on collection view
and @josejuanqm 's solution is not working for me.

**Comment by NikhilGangurde** [comment]
> @josejuanqm I dug into the code and realized that disabling the pan gesture fixes the issue.
> 
> While instantiating the player view, I do the following:
> 
> ```
> if let swipeGesture = videoPlayer.controls.controlsCoordinator.gestureReciever.panGesture{
>    videoPlayer.controls.controlsCoordinator.gestureReciever.removeGestureRecognizer(swipeGesture)
>    videoPlayer.controls.controlsCoordinator.gestureReciever.panGesture = nil
> }
> ```
> 
> Is it the correct way or there is some other way to remove a particular gesture?

Worked for me as well👍🏻
