### ISSUE TITLE
TV test app crashes on launch in tvOS 13

### ISSUE THREAD

**Issue by hbmartin** [josejuanqm/VersaPlayer#53]
The sample TV app crashes on launch, with an error that seems nib related:
```
VersaPlayerTest_tvOS[69831:7967219] [Storyboard] Unknown class
_TtC20VersaPlayerTest_tvOS19VersaPlayerControls in Interface Builder
file.
```

**Comment by josejuanqm** [comment]
Hi @hbmartin ,

Ive pushed some changes to avoid this to happen on the sample project.

Thanks!

**Comment by gurhub** [comment]
Hi, still the same issue exists in the example project. 

Best

**Comment by hbmartin** [comment]
I am getting `VersaPlayerTest_tvOS[10533:4896726] [Storyboard] Unknown class _TtC20VersaPlayerTest_tvOS15VersaPlayerView in Interface Builder file.`
