### ISSUE TITLE
Crashes sometimes

### ISSUE THREAD

**Issue by dev-dubaisoftwaresolutions** [josejuanqm/VersaPlayer#54]
App crashes sometimes, attached is the screenshot from stack trace.
Any help?
![Screen Shot 2019-11-26 at 9 19 19 AM](https://user-images.githubusercontent.com/42694125/69601546-e6349580-102d-11ea-8d13-cc19d39bb28b.png)

**Comment by RajChanchal** [comment]
Same happened after the recent update of the repo as well

<img width="529" alt="Screen Shot 2019-12-06 at 2 20 13 PM" src="https://user-images.githubusercontent.com/7058465/70315748-b35f7e00-1833-11ea-89b9-00980744e2fa.png">

**Comment by josejuanqm** [comment]
Tentatively fixed by version 3.0.2. Please verify. And thank you both!
