### ISSUE TITLE
Mute/Unmute?

### ISSUE THREAD

**Issue by StackHelp** [josejuanqm/VersaPlayer#55]
How to mute/unmute player? Is there any control there for it?

**Comment by josejuanqm** [comment]
Hi @StackHelp ,  I've created this feature in a dev branch `enhancement/mute` , let me know if this works for you so that I can merge and update the pod.

**Comment by StackHelp** [comment]
Yeah great. Thanks. Can we also have the property in the player class, so we can also mute/unmute without button as well? Is it possible? The one more thing, Is there any label that gives us remaining time? like one is total time, other is one for current time. so, Is there any for remaining time?

**Comment by josejuanqm** [comment]
You can use the VersaPlayerView to toggle the mute.

As of right now there is no remaining time label. I can work on that tomorrow.

**Comment by StackHelp** [comment]
ok. Thanks  @josejuanqm

**Comment by Edgy1337** [comment]
Re-open?
