### ISSUE TITLE
Crash found on label `currentTimeLabel?.update` 

### ISSUE THREAD

**Issue by StackHelp** [josejuanqm/VersaPlayer#57]
Whenever I tried to play video, It aways crashed on line `currentTimeLabel?.update`, VersaPlayerControls, line number 128. Here are some screenshot related to that

![Screenshot 2019-12-13 at 10 26 08 AM](https://user-images.githubusercontent.com/41230403/70770552-db9b2f80-1d93-11ea-8345-24b0298d4d8b.png)
![Screenshot 2019-12-13 at 10 28 58 AM](https://user-images.githubusercontent.com/41230403/70770554-dccc5c80-1d93-11ea-826e-b8681151807c.png)
![Screenshot 2019-12-13 at 10 36 07 AM](https://user-images.githubusercontent.com/41230403/70770701-654afd00-1d94-11ea-8bb5-0dd150596537.png)

**Comment by josejuanqm** [comment]
Hi, 

Does this happen on the example project? Also, Can you post the version of Xcode and iOS (or any other os) you're using?

Thanks

**Comment by StackHelp** [comment]
@josejuanqm No, but its the same way I made the outlet for labels

**Comment by StackHelp** [comment]
@josejuanqm  Ohhh!! I found the issue. I have set the outlets but not give a class to the label. Sorry about that. Anyway great Video player :) And Hope caching will come soon in this SDK.

**Comment by josejuanqm** [comment]
Thanks a lot! Will try to work on that soon!
