### ISSUE TITLE
add faster speed playback

### ISSUE THREAD

**Issue by m3u8playlist** [josejuanqm/VersaPlayer#58]
Hi developer
do you have any plan to add faster speed playback option?
like 1.0x(original speed), 1.2x,1.5x, etc. speed to playback m3u8 videos

**Comment by josejuanqm** [comment]
Hi @m3u8playlist , are you talking about streams, or local files?

**Comment by m3u8playlist** [comment]
> Hi @m3u8playlist , are you talking about streams, or local files?
online m3u8 , like movie or tv episode
https://shuixian.nihaozuida.com/20200229/867_443e38a8/index.m3u8

**Comment by josejuanqm** [comment]
Yes, you could access the internal player and use the speed parameter. will try to put this on the controls, although the ui is something that you should implement. If the stream is a livestream this wont work though.
