### ISSUE TITLE
Is it possible to set more height for player controls than the player view?

### ISSUE THREAD

**Issue by StackHelp** [josejuanqm/VersaPlayer#61]
Is it possible to set more height for player controls than the player view? I have attached a screenshot where you can see the player view is that black background colored part above pink one and above there is controls setup with more height that extends till pink color starting from player view top. The problem is with the setup is touch isn't repond on that pink part but responds on playerview part

![Screenshot 2020-03-02 at 3 33 26 PM](https://user-images.githubusercontent.com/41230403/75666097-3fe6d480-5c9b-11ea-9bad-d592dbd852c8.png)

**Desktop **
 - iOS

**Comment by josejuanqm** [comment]
Hi @StackHelp , Yes, the controls view is independent from the rendering view, so you can have the controls view detached from the player view completely (ui-wise).

However you might find yourself wanting to use a different behaviour that the default one for buffering and showing / hiding controls.

**Comment by StackHelp** [comment]
@josejuanqm its completely independent right now like in screenshot its above `player View`. But somehow none of the buttons from the pink part works (By independent means? any Example to used it like that) and I also don't want to hide controls even on touch. I used `playerControls.behaviour.shouldHideControls = false` but it still hides on touch.

**Comment by josejuanqm** [comment]
hmmm, is there a chance you can send over a sample project?

**Comment by StackHelp** [comment]
@josejuanqm I managed to work this out by some awkward steps like use the controls view for black area same as example project and on other buttons, I just assigned to player view.

```
        playerView.use(controls: playerControls)
        playerView.controls?.playPauseButton = playPauseButton
        playerView.controls?.fullscreenButton = fullScreenButton
        playerView.isFullscreenModeEnabled = true
        playerView.controls?.prepare()
```

however, on `fullscreenButton`, I got a crash for nil `handler`
`VersaPlayer/VersaPlayer/Classes/Source/VersaPlayerControls/VersaPlayerControls.swift, line 371`

**Comment by josejuanqm** [comment]
hmmm, let me test this and get back to you.

**Comment by anilchandel** [comment]
Is it possible to set more height of PlayerView and play video. automatically landscape. and also possible  to set the video quality.
