### ISSUE TITLE
Can not toggle the fullscreen and how to replay?

### ISSUE THREAD

**Issue by mrsniperz** [josejuanqm/VersaPlayer#65]
**Describe the bug**
After I press the fullscreen button I can't toggle it back to normal screen.

**To Reproduce**
![image](https://user-images.githubusercontent.com/35944209/78921662-d0e57280-7ac7-11ea-9cc9-61d4b63fbb47.png)
When i toggle the fullscreen button, it gives the message as in the image .

Another question is when it finished how to replay it through press some button?

**Comment by AhmedAbdeen11** [comment]
I'm facing same issue. Did you manage to solve it?

**Comment by fadizant** [comment]
To avoid this issue you have to add VersaPlayerView inside other view and add all edges constrains to new superview

![image](https://user-images.githubusercontent.com/13743626/95501907-aeb6a980-09b1-11eb-8bc4-dc4efd9b6ef2.png)
