### ISSUE TITLE
Could not cast value of type 'CALayer' to 'AVPlayerLayer'. Crash

### ISSUE THREAD

**Issue by kunwar231** [josejuanqm/VersaPlayer#66]
Could not cast value of type 'CALayer' (0x7fff84dce660) to 'AVPlayerLayer' (0x7fff84af1118).
in VersaPlayerRenderingView.swift

**Comment by reyesmfabian** [comment]
Was anyone able to solve the problem indicated by @kunwar231? I have the same problem, the application compiles correctly but when I open a URL the error is shown.
