### ISSUE TITLE
Setting the quality of the video playback depending on network speed

### ISSUE THREAD

**Issue by niftykurian** [josejuanqm/VersaPlayer#68]
**Is your feature request related to a problem? Please describe.**
Hi, This library is great. Thanks! 
Many parts of the world, the network speed is very slow, and there is no option to set the quality of the video played

**Describe the solution you'd like**
Set the quality of the video playback depending on network speed/ option to change the quality.

**Comment by josejuanqm** [comment]
Hi @niftykurian , are you using tracks to switch them? You might need to provide the proper tracks in each bitrate.

**Comment by fadizant** [comment]
I have the same issue here. it's will be helpful if we have control of quality and auto-switch when we have a slow internet connection.
this example video has multi quality: https://content.jwplatform.com/manifests/yp34SRmf.m3u8
you can see it from here: https://www.jwplayer.com/developers/stream-tester/

![image](https://user-images.githubusercontent.com/13743626/95473336-ac8e2400-098c-11eb-88f9-1c1ffb104a62.png)
