### ISSUE TITLE
TV test app crashes on launch

### ISSUE THREAD

**Issue by gouravideal** [josejuanqm/VersaPlayer#72]
Could not cast value of type 'CALayer' (0x7fff84dce660) to 'AVPlayerLayer' (0x7fff84af1118).
![Screenshot 2020-09-26 at 6 47 36 PM](https://user-images.githubusercontent.com/61136324/94341664-c80e3c00-0028-11eb-9da7-fa3aa3b311f7.png)

**Comment by gouravideal** [comment]
@josejuanqm can you please solution for this issue i want to use this for TVOS

**Comment by Marware** [comment]
This is fixed here by removing #if os(iOS) directive

**Comment by reyesmfabian** [comment]
Was anyone able to solve the problem indicated by @gouravideal ? I have the same problem, the application compiles correctly but when I open a URL the error is shown.
