### ISSUE TITLE
Facing one crash while i try to use VersaPlayerControls

### ISSUE THREAD

**Issue by Disha896** [josejuanqm/VersaPlayer#90]
private func checkOwnershipOf(object: Any?, completion: @autoclosure ()->()?) {
      guard let ownerPlayer = object as? VersaPlayer else { return }
      if ownerPlayer.isEqual(handler?.player) {
        completion()
      }
    }

I have added versaplayerview in one XIB and added versaplayercontrs ciew in View controller and connected with outlets to viewcontroller. 
My app is getting crashed at this completion() call. I am not getting any other logs in debug.
can you please guide what reason it can be. 
Let me know if I can provide any detailed explanation about implementation.

Warnings I am getting in log :
[MediaRemote] [AVOutputContext] WARNING: AVF context unavailable for +[MRAVOutputContext sharedAudioPresentationContext]_block_invoke
[MediaRemote] [AVOutputContext] WARNING: AVF context unavailable for SYSTEM

**Desktop**
 - OS: MAC OS 10.15.3

**DEVICE:**
 - Device: iPhone11
 - OS: iOS13.4.1

**Comment by josejuanqm** [comment]
Hi @Disha896 could you share the stack trace?
